// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFiles(arg1) {
  return window['go']['main']['App']['AnalyzeFiles'](arg1);
}

export function CancelAnalysis() {
  return window['go']['main']['App']['CancelAnalysis']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CancelSmartScan() {
  return window['go']['main']['App']['CancelSmartScan']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Cleanup(arg1) {
  return window['go']['main']['App']['Cleanup'](arg1);
}

export function ClearCleanableItems(arg1) {
  return window['go']['main']['App']['ClearCleanableItems'](arg1);
}

export function GetActiveLLMConfig() {
  return window['go']['main']['App']['GetActiveLLMConfig']();
}

export function GetCleanableItems(arg1) {
  return window['go']['main']['App']['GetCleanableItems'](arg1);
}

export function GetCleanableSize(arg1) {
  return window['go']['main']['App']['GetCleanableSize'](arg1);
}

export function GetLLMConfigs() {
  return window['go']['main']['App']['GetLLMConfigs']();
}

export function GetQuickTargets() {
  return window['go']['main']['App']['GetQuickTargets']();
}

export function GetRecentCleanups(arg1) {
  return window['go']['main']['App']['GetRecentCleanups'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemDrives() {
  return window['go']['main']['App']['GetSystemDrives']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function SaveLLMConfig(arg1) {
  return window['go']['main']['App']['SaveLLMConfig'](arg1);
}

export function Scan(arg1, arg2) {
  return window['go']['main']['App']['Scan'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SmartScan(arg1, arg2) {
  return window['go']['main']['App']['SmartScan'](arg1, arg2);
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}
