// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {main} from '../models';
import {cleaner} from '../models';
import {llm} from '../models';
import {store} from '../models';
import {platform} from '../models';

export function AnalyzeFiles(arg1:Array<scanner.FileEntry>):Promise<void>;

export function CancelAnalysis():Promise<void>;

export function CancelScan():Promise<void>;

export function CancelSmartScan():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function Cleanup(arg1:Array<cleaner.CleanupItem>):Promise<Array<cleaner.CleanupResult>>;

export function ClearCleanableItems(arg1:string):Promise<void>;

export function GetActiveLLMConfig():Promise<llm.LLMConfig>;

export function GetCleanableItems(arg1:string):Promise<Array<store.CleanableItemDB>>;

export function GetCleanableSize(arg1:string):Promise<number>;

export function GetLLMConfigs():Promise<Array<store.LLMConfig>>;

export function GetQuickTargets():Promise<Array<platform.QuickTarget>>;

export function GetRecentCleanups(arg1:number):Promise<Array<store.CleanupLog>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSystemDrives():Promise<Array<platform.DriveInfo>>;

export function GetVersion():Promise<string>;

export function SaveLLMConfig(arg1:llm.LLMConfig):Promise<void>;

export function Scan(arg1:string,arg2:scanner.ScanOptions):Promise<scanner.ScanResult>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SmartScan(arg1:string,arg2:scanner.ScanOptions):Promise<void>;

export function TestLLMConnection(arg1:llm.LLMConfig):Promise<llm.ConnectionTestResult>;
